{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4417d1d1-b952-4416-83b7-5a21dc174f39",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app '__main__' (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/deps/polyfill@7.v2_3_1m1650390307.12.1.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/deps/react-dom@16.v2_3_1m1650390307.14.0.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/deps/react@16.v2_3_1m1650390307.14.0.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/deps/prop-types@15.v2_3_1m1650390307.7.2.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_3_1m1650390303.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/dcc/dash_core_components.v2_3_0m1650390307.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_3_0m1650390307.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/html/dash_html_components.v2_0_2m1650390316.min.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/dash_table/bundle.v5_1_1m1650390306.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_favicon.ico?v=2.3.1 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:22] \"\u001b[37mGET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:23] \"\u001b[37mGET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:23] \"\u001b[37mGET /_dash-component-suites/dash/dcc/async-slider.js HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [06/May/2022 16:42:23] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:23] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 306, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 294, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2095, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2080, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1434, in handle_exception\n",
      "    server_error = InternalServerError(original_exception=e)\n",
      "TypeError: __init__() got an unexpected keyword argument 'original_exception'\n",
      "Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 306, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 294, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2095, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2080, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1434, in handle_exception\n",
      "    server_error = InternalServerError(original_exception=e)\n",
      "TypeError: __init__() got an unexpected keyword argument 'original_exception'\n",
      "127.0.0.1 - - [06/May/2022 16:42:23] \"\u001b[37mGET /_favicon.ico?v=2.3.1 HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [06/May/2022 16:42:32] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:32] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 306, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 294, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2095, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2080, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1434, in handle_exception\n",
      "    server_error = InternalServerError(original_exception=e)\n",
      "TypeError: __init__() got an unexpected keyword argument 'original_exception'\n",
      "Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 306, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 294, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2095, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2080, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1434, in handle_exception\n",
      "    server_error = InternalServerError(original_exception=e)\n",
      "TypeError: __init__() got an unexpected keyword argument 'original_exception'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [06/May/2022 16:42:35] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [06/May/2022 16:42:35] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 306, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 294, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2095, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2080, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1434, in handle_exception\n",
      "    server_error = InternalServerError(original_exception=e)\n",
      "TypeError: __init__() got an unexpected keyword argument 'original_exception'\n",
      "Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1315, in dispatch\n",
      "    body = flask.request.get_json()\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\local.py\", line 348, in __getattr__\n",
      "    return getattr(self._get_current_object(), name)\n",
      "AttributeError: 'Request' object has no attribute 'get_json'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 306, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\werkzeug\\serving.py\", line 294, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2095, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2080, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"C:\\Users\\Personal\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1434, in handle_exception\n",
      "    server_error = InternalServerError(original_exception=e)\n",
      "TypeError: __init__() got an unexpected keyword argument 'original_exception'\n"
     ]
    }
   ],
   "source": [
    "# Import required libraries\n",
    "import pandas as pd\n",
    "from dash import Dash, dcc, html, Input, Output\n",
    "#import dash_html_components as html\n",
    "#import dash_core_components as dcc\n",
    "#from dash.dependencies import Input, Output\n",
    "import plotly.express as px\n",
    "\n",
    "# Read the airline data into pandas dataframe\n",
    "spacex_df = pd.read_csv(\"spacex_launch_dash.csv\")\n",
    "max_payload = spacex_df['Payload Mass (kg)'].max()\n",
    "min_payload = spacex_df['Payload Mass (kg)'].min()\n",
    "\n",
    "# Create a dash application\n",
    "app = Dash(__name__)\n",
    "\n",
    "# Create an app layout\n",
    "app.layout = html.Div(children=[html.H1('SpaceX Launch Records Dashboard',\n",
    "                                        style={'textAlign': 'center', 'color': '#503D36',\n",
    "                                               'font-size': 40}),\n",
    "                                # TASK 1: Add a dropdown list to enable Launch Site selection\n",
    "                                # The default select value is for ALL sites\n",
    "                                # dcc.Dropdown(id='site-dropdown',...)\n",
    "                                html.Br(),\n",
    "                                dcc.Dropdown(id='site-dropdown',options=[{'label': 'All Sites', 'value': 'ALL'},\n",
    "                                                                             {'label': 'CCAFS LC-40', 'value': 'CCAFS LC-40'},\n",
    "                                                                             {'label': 'CCAFS SLC-40', 'value': 'CCAFS SLC-40'},\n",
    "                                                                             {'label': 'KSC LC-39A', 'value': 'KSC LC-39A'},\n",
    "                                                                             {'label': 'VAFB SLC-4E', 'value': 'VAFB SLC-4E'}],\n",
    "                                              value='ALL',\n",
    "                                              placeholder='Select a Launch Site here',\n",
    "                                              searchable=True),\n",
    "\n",
    "\n",
    "                                # TASK 2: Add a pie chart to show the total successful launches count for all sites\n",
    "                                # If a specific launch site was selected, show the Success vs. Failed counts for the site\n",
    "                                html.Div(dcc.Graph(id='success-pie-chart')),\n",
    "                                html.Br(),\n",
    "\n",
    "                                html.P(\"Payload range (Kg):\"),\n",
    "                                # TASK 3: Add a slider to select payload range\n",
    "                                #dcc.RangeSlider(id='payload-slider',...)\n",
    "                                dcc.RangeSlider(id='payload-slider',min=0, max=10000,\n",
    "                                marks={0:'0',10000:'10000'},\n",
    "                                step=1000,value=[min_payload,max_payload]),\n",
    "\n",
    "                                # TASK 4: Add a scatter chart to show the correlation between payload and launch success\n",
    "                                html.Div(dcc.Graph(id='success-payload-scatter-chart')),\n",
    "                                ])\n",
    "\n",
    "# TASK 2:\n",
    "# Add a callback function for `site-dropdown` as input, `success-pie-chart` as output\n",
    "@app.callback(\n",
    "    Output(component_id='success-pie-chart',component_property='figure'),\n",
    "    Input(component_id='site-dropdown',component_property='value')\n",
    ")\n",
    "def get_pie_chart(entered_site):\n",
    "    filtered_df=spacex_df\n",
    "    if entered_site=='ALL':\n",
    "        fig=px.pie(filtered_df,values='class',\n",
    "        names='Launch Site',\n",
    "        title='Total Success Launches by all sites') \n",
    "        return fig\n",
    "    else:\n",
    "        filtered_df=spacex_df[spacex_df['Launch Site']==entered_site] \n",
    "        fig=px.pie(filtered_df,\n",
    "        names='class',\n",
    "        title='Total success launches for '+ entered_site) \n",
    "        return fig\n",
    "# TASK 4:\n",
    "# Add a callback function for `site-dropdown` and `payload-slider` as inputs, `success-payload-scatter-chart` as output\n",
    "@app.callback(Output(component_id='success-payload-scatter-chart',component_property='figure'),\n",
    "              [Input(component_id='site-dropdown',component_property='value'),\n",
    "               Input(component_id='payload-slider',component_property='value')]\n",
    ")\n",
    "def get_scatter(site,payload):\n",
    "    filtered_df=spacex_df[spacex_df['Payload Mass (kg)'].between(payload[0],payload[1])]\n",
    "    if site=='ALL':\n",
    "        fig=px.scatter(filtered_df,x='Payload Mass (kg)',y='class',\n",
    "        color='Booster Version Category',\n",
    "        title='Total Success Launches by all sites')\n",
    "        return fig\n",
    "    else:\n",
    "        filtered_df=filtered_df[filtered_df['Launch Site']==site]\n",
    "        fig=px.scatter(filtered_df,x='Payload Mass (kg)',y='class',\n",
    "        color='Booster Version Category',\n",
    "        title='Total success launches for '+ site)\n",
    "        return fig\n",
    "\n",
    "\n",
    "\n",
    "# Run the app\n",
    "if __name__ == '__main__':\n",
    "    app.run_server()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "47753846-6893-499a-a951-ab22d5e17e53",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
